### ISSUE TITLE
Wrong order in } escaping

### ISSUE THREAD

**Issue by ruphy** [softcover/polytexnic#109]
Hello,
the issue is very simple. Given the following Markdown:

    MathJax riconosca bene sia * che \texttt{\ast{}}.

Polytexnic produces the following LaTeX code

    MathJax riconosca bene sia * che \texttt{\\ast{}\}.

which results in the document not to compile. The expected result is:

    MathJax riconosca bene sia * che \texttt{\\ast\{\}}.

Note that even adding the text in the initial Markdown as

    MathJax riconosca bene sia * che \texttt{\\ast\{\}}.

results in

    MathJax riconosca bene sia * che \texttt{\\ast\{\}\}.

**Comment by mhartl** [comment]
Thanks for the report. As mentioned in [Section 3.1.3](http://manual.softcover.io/book/softcover_markdown#sec-miscellaneous_features) and detailed in [Section 3.3.1](http://manual.softcover.io/book/softcover_markdown#sec-embedded_latex_commands), typesetting raw LaTeX commands is best done using the inline verbatim environment, as follows:

```latex
MathJax riconosca bene sia * che \verb+\ast{}+.
```

Hope this helps.
