### ISSUE TITLE
Possible minimal binary doing just the latex -> xml -> html part?

### ISSUE THREAD

**Issue by j2kun** [softcover/polytexnic#115]
Hi there,

I'm able to run tralics on a latex file [1], and I'd like to know if it is possible to use this project to set up a simple binary that just does the latex -> xml -> html part, taking advantage of the pre/postprocessing done here already for things like code listings.

Would this be feasible to set up the way the project is structured?

[1]: There are some errors, since the documentclass is `memoir` which is not in tralics's standard confdir, but I can worry about that later.

**Comment by mhartl** [comment]
A proper binary isn’t likely, but it might be possible to incorporate what you want into a Ruby script.
