### ISSUE TITLE
Canonical method of setting  list spacing? 

### ISSUE THREAD

**Issue by archerships** [softcover/polytexnic#128]
I'm writing a book in PolyTex, and I'd like to reduce the space separating list items.  

Right now, this code: 

\begin{itemize}
    \item All USVI citizens. 
    \item Anyone who yearns for more freedom in their lifetime.
\end{itemize}

...produces a list with  double spacing.  (See attached image).  

![softcover-list](https://github.com/softcover/polytexnic/assets/77993343/246f4508-6209-4168-aa55-d8d5d2ae99a9)

I'd like to change the spacing to match the spacing of Markdown list items:

https://manual.softcover.io/book/introduction_to_markdown 

Most tutorials specify using the enumitem package, which doesn't appear to work: 

https://www.latex-tutorial.com/tutorials/lists/

Thanks in advance for any assistance.

**Comment by mhartl** [comment]
Thanks for your question. Custom styling of the sort you’re interested in is covered in [Section 4.2](https://manual.softcover.io/book/customization#sec-commands_and_styles) of the Softcover manual. Briefly, LaTeX packages like enumitem can be included in `latex_styles/custom.sty` to style PDF output and CSS rules can be included in `html/stylesheets/custom.css` to style HTML/EPUB/MOBI output.

**Comment by archerships** [comment]
Many thanks!
